main: com.koletar.jj.chestkeeper.ChestKeeper
name: ChestKeeper
version: $version$
author: jjkoletar
softdepend: [Vault]
commands:
  chestkeeper:
    aliases: [ck, gp, vc, chest]
    description: Manage your ChestKeeper.
    usage: /chestkeeper <subcommand>